# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger: none

name: $(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'


steps:
- script: docker login $ACR_URL -u $ACR_USERNAME -p $ACR_KEY
  env:
    ACR_KEY: $(ACR_KEY)
    ACR_URL: $(ACR_URL)
    AZ_SUBSCRIPTION: $(AZ_SUBSCRIPTION)
    ACR_USERNAME: $(ACR_USERNAME)
  displayName: 'docker login'

- task: DockerCompose@0
  displayName: Build services
  inputs:
    action: Build services
    azureSubscriptionEndpoint: $(AZ_SUBSCRIPTION)
    azureContainerRegistry: $(ACR_URL)
    dockerComposeFile: docker-compose.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    includeLatestTag: true
    additionalImageTags: $(Build.BuildID)

- task: DockerCompose@0
  displayName: Push services
  inputs:
    action: Push services
    azureSubscriptionEndpoint: $(AZ_SUBSCRIPTION)
    azureContainerRegistry: $(ACR_URL)
    dockerComposeFile: docker-compose.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    includeLatestTag: true
    additionalImageTags: $(Build.BuildID)

