# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger: none

name: $(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureContainerRegistry: $(ACR_URL)
  azureSubscriptionEndpoint: $(AZ_SUBSCRIPTION)

steps:
- script: docker login $ACR_URL -u $ACR_NAME -p $DOCKER_LOGIN_PASSWORD
  env:
    DOCKER_LOGIN_PASSWORD: $(ACR_KEY)
    ACR_URL: $(ACR_URL)
    AZ_SUBSCRIPTION: $(AZ_SUBSCRIPTION)
    ACR_NAME: $(ACR_NAME)
  displayName: 'docker login'

- task: DockerCompose@0
  displayName: Build services
  inputs:
    action: Build services
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker-compose.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    includeLatestTag: true
    additionalImageTags: $(Build.BuildID)

- task: DockerCompose@0
  displayName: Push services
  inputs:
    action: Push services
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker-compose.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    includeLatestTag: true
    additionalImageTags: $(Build.BuildID)

